---
# tasks file for apigee-opdk-setup-apigee-user
- name: Create the apigee group
  become: yes
  group:
    name: "{{ opdk_group_name }}"
    state: present
  when: opdk_group_create | default(True)

- name: Create the apigee user
  become: yes
  user:
    name: "{{ opdk_user_name }}"
    comment: "OPDK user"
    group: "{{ opdk_group_name }}"

- name: Ensure that OPDK staging folder is in place
  become: yes
  file:
    path: '{{ opdk_resources_path }}'
    state: directory
    group: '{{ opdk_group_name }}'
    owner: '{{ opdk_user_name }}'
    recurse: yes
    mode: 0755
