---
# tasks file for apigee-opdk-setup-apigee-user
- name: Create the apigee group
  become: yes
  group:
    name: "{{ opdk_group_name }}"
    state: present

- name: Create the apigee user
  become: yes
  user:
    name: "{{ opdk_user_name }}"
    comment: "OPDK user"
    group: "{{ opdk_group_name }}"
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa

- name: Ensure that OPDK staging folder is in place
  file:
    path: '{{ opdk_installer_path }}'
    state: directory
    group: '{{ opdk_group_name }}'
    owner: '{{ opdk_user_name }}'
    recurse: yes
    mode: 0755

- name: Installation home stats
  stat:
    path: '{{ apigee_home }}'

- name: Setup permission for apigee installation home directory
  file:
    path: '{{ apigee_home }}'
    group: '{{ opdk_group_name }}'
    owner: '{{ opdk_user_name }}'
    mode: 0755
    state: directory
